### ISSUE TITLE
dummy

### ISSUE THREAD

**Issue by pkofod** [pkofod/PlotThemes.jl#1]

**Comment by pkofod** [comment]
![pyplots](https://cloud.githubusercontent.com/assets/8431156/19212997/4597a80e-8d60-11e6-9c16-6c4171964a7e.png)

**Comment by pkofod** [comment]
pyplot dark

**Comment by pkofod** [comment]
![pyplots](https://cloud.githubusercontent.com/assets/8431156/19213171/410c6370-8d64-11e6-8cbe-d73cbb61ddad.png)
pyplot dark 2 (StatPlots changes only)

**Comment by pkofod** [comment]
![pyplots](https://cloud.githubusercontent.com/assets/8431156/19213193/ff73747a-8d64-11e6-9a96-4cc3c5b802f5.png)
pyplot dark 3 (More changes to StatPlots)

and defaults
![defaults](https://cloud.githubusercontent.com/assets/8431156/19213199/1e1feb42-8d65-11e6-8573-7b9289ad11f9.png)

**Comment by pkofod** [comment]
![pyplots](https://cloud.githubusercontent.com/assets/8431156/19215305/8931f030-8d9a-11e6-9b15-011c19ff7456.png)
d fixed

**Comment by pkofod** [comment]
![sand](https://cloud.githubusercontent.com/assets/8431156/19215525/02fbf8f6-8da1-11e6-9ef8-09d74fc802a0.png)
sand

**Comment by pkofod** [comment]
![solarized](https://cloud.githubusercontent.com/assets/8431156/19223370/3e081ccc-8e6e-11e6-88de-292f329b03a7.png)
![solarized_light](https://cloud.githubusercontent.com/assets/8431156/19223371/3f45672a-8e6e-11e6-827a-4425119ca978.png)
 solarized

**Comment by pkofod** [comment]
![solarized_light](https://cloud.githubusercontent.com/assets/8431156/19223536/80e12616-8e72-11e6-9085-daca2e88baf3.png)
![solarized](https://cloud.githubusercontent.com/assets/8431156/19223543/a37b0c78-8e72-11e6-8c99-27d8cc0db403.png)
solarized

**Comment by pkofod** [comment]
![solarized](https://cloud.githubusercontent.com/assets/8431156/19230182/6c0a2d08-8ed3-11e6-8ad8-aa46a3f67f90.png)
![solarized_light](https://cloud.githubusercontent.com/assets/8431156/19230183/6d5edb90-8ed3-11e6-927f-5729f888b2d7.png)
![dark](https://cloud.githubusercontent.com/assets/8431156/19230231/c321be26-8ed3-11e6-9f17-c398d8840245.png)
![sand](https://cloud.githubusercontent.com/assets/8431156/19230234/c4a77d6c-8ed3-11e6-8226-df8874a2e9d3.png)

**Comment by pkofod** [comment]
![dark](https://cloud.githubusercontent.com/assets/8431156/19231320/b586c026-8ed9-11e6-989a-c7f181ce8e1d.png)
![sand](https://cloud.githubusercontent.com/assets/8431156/19231322/b587c048-8ed9-11e6-824c-a6f8098b576c.png)
![solarized](https://cloud.githubusercontent.com/assets/8431156/19231323/b58bf5a0-8ed9-11e6-81c0-3547a0201615.png)
![solarized_light](https://cloud.githubusercontent.com/assets/8431156/19231321/b5872ebc-8ed9-11e6-8a5b-a9b615e348a9.png)

**Comment by pkofod** [comment]
![contrast](https://cloud.githubusercontent.com/assets/8431156/19234379/87084ff0-8eeb-11e6-81bd-5e6abada0082.png)

**Comment by pkofod** [comment]
![orange](https://cloud.githubusercontent.com/assets/8431156/19236422/9aadc056-8ef7-11e6-83ad-5eb89e45680f.png)

**Comment by daschw** [comment]
Updated readme images:

`:default`:
![plottheme_default](https://user-images.githubusercontent.com/16589944/33489485-4b3c190e-d6b4-11e7-90c7-b58b35b735ac.png)

`:dark`:
![plottheme_dark](https://user-images.githubusercontent.com/16589944/33489504-511a882e-d6b4-11e7-8b4d-64c54f926b7c.png)

`:sand`:
![plottheme_sand](https://user-images.githubusercontent.com/16589944/33489509-568adb42-d6b4-11e7-8529-e32602edce20.png)

`:lime`:
![plottheme_lime](https://user-images.githubusercontent.com/16589944/33489523-5dbe46c4-d6b4-11e7-9976-4c217f299408.png)

`:orange`:
![plottheme_orange](https://user-images.githubusercontent.com/16589944/33489526-60efe2bc-d6b4-11e7-958d-07e766adf849.png)

`:solarized`:
![plottheme_solarized](https://user-images.githubusercontent.com/16589944/33489533-6500a21a-d6b4-11e7-9f02-a44e1066a20a.png)

`:solarized_light`:
![plottheme_solarized_light](https://user-images.githubusercontent.com/16589944/33489539-6948e4ea-d6b4-11e7-879e-b9943607d263.png)

`:juno`:
![plottheme_juno](https://user-images.githubusercontent.com/16589944/33489542-713aa45e-d6b4-11e7-8385-558819e9d47c.png)

**Comment by daschw** [comment]
![theme_default](https://user-images.githubusercontent.com/16589944/34081411-90c3699c-e34c-11e7-9c64-ea7aae0f066d.png)
![theme_dark](https://user-images.githubusercontent.com/16589944/34081412-928bd96c-e34c-11e7-95be-744a9f1eb19a.png)
![theme_ggplot2](https://user-images.githubusercontent.com/16589944/34081416-943c5ca0-e34c-11e7-8b45-74f61d958c47.png)
![theme_juno](https://user-images.githubusercontent.com/16589944/34081419-9632675c-e34c-11e7-8673-d959eb242059.png)
![theme_lime](https://user-images.githubusercontent.com/16589944/34081420-97ff3c4a-e34c-11e7-96fc-4ce5d569180c.png)
![theme_orange](https://user-images.githubusercontent.com/16589944/34081422-9a4d009a-e34c-11e7-816a-ccb796d61e4b.png)
![theme_sand](https://user-images.githubusercontent.com/16589944/34081423-9c79b660-e34c-11e7-8861-efc2d13efd30.png)
![theme_solarized](https://user-images.githubusercontent.com/16589944/34081424-9de1d9b0-e34c-11e7-9aa2-efa112e77e2d.png)
![theme_solarized_light](https://user-images.githubusercontent.com/16589944/34081426-9f4371e2-e34c-11e7-8f9c-838232d51843.png)
![theme_wong](https://user-images.githubusercontent.com/16589944/34081427-a12508d6-e34c-11e7-8767-b66fa276b298.png)
![theme_wong2](https://user-images.githubusercontent.com/16589944/34081428-a340fa3a-e34c-11e7-83a4-d671ba25a441.png)

**Comment by mkborregaard** [comment]
Very pretty with the new showtheme command. One thing that becomes clear is that we should consider adding "real" gradients (from the PlotUtils colorlibraries) that match the colors to all the themes, for better quality.

**Comment by mkborregaard** [comment]
Also, the gridlines on the 3-d plot appears to behave strangely - is that from the backend?

**Comment by pkofod** [comment]
> Very pretty with the new showtheme command. One thing that becomes clear is that we should consider adding "real" gradients (from the PlotUtils colorlibraries) that match the colors to all the themes, for better quality.

You're talking about the heatmaps and surface plots right?

**Comment by mkborregaard** [comment]
The three below panels, yes

**Comment by pkofod** [comment]
> The three below panels, yes

Yes, many of them are very hard to visually interpret

**Comment by mkborregaard** [comment]
:+1: I'll try to suggest some replacement gradients tomorrow. I'm lecturing 3 hours in the morning so I have to prepare now - time to stop procrastinating on github

**Comment by pkofod** [comment]
> :+1: I'll try to suggest some replacement gradients tomorrow. I'm lecturing 3 hours in the morning so I have to prepare now - time to stop procrastinating on github

I've told you before, just show them Blue Planet II and keep on working on OSS!

**Comment by mkborregaard** [comment]
The solarized gradients could use `:YlOrRd` or `:YlOrRd_r`. Juno and Dark could both use `:fire`. All the green ones could use :viridis . Not sure about sand - `:dense`?

**Comment by mkborregaard** [comment]
Dark
<img width="440" alt="skaermbillede 2017-12-18 kl 22 13 33" src="https://user-images.githubusercontent.com/8429802/34128511-405d6bec-e441-11e7-8adb-ded142920cc6.png">
Juno
<img width="469" alt="skaermbillede 2017-12-18 kl 22 13 18" src="https://user-images.githubusercontent.com/8429802/34128517-466bdd2a-e441-11e7-9b0d-9f2198c9a945.png">
Lime:
<img width="461" alt="skaermbillede 2017-12-18 kl 22 14 07" src="https://user-images.githubusercontent.com/8429802/34128523-4e3bf2e2-e441-11e7-984d-3f27823826e6.png">
Orange:
<img width="453" alt="skaermbillede 2017-12-18 kl 22 15 14" src="https://user-images.githubusercontent.com/8429802/34128528-5348625c-e441-11e7-9455-ea036ccfa66b.png">
Solarized:
<img width="454" alt="skaermbillede 2017-12-18 kl 22 15 52" src="https://user-images.githubusercontent.com/8429802/34128532-5c291920-e441-11e7-867d-6b7f84cc6572.png">
Solarized_light
<img width="450" alt="skaermbillede 2017-12-18 kl 22 16 09" src="https://user-images.githubusercontent.com/8429802/34128552-63a42fd2-e441-11e7-81dc-35b2674775c0.png">
sand:
<img width="450" alt="skaermbillede 2017-12-18 kl 22 16 42" src="https://user-images.githubusercontent.com/8429802/34128560-6839e334-e441-11e7-9c62-a5c37e4fc820.png">
Really not sure, these are just quick suggestions.

**Comment by daschw** [comment]
The 3d grid issue is a gr issue and should be fixed in https://github.com/JuliaPlots/Plots.jl/pull/1328.
+1 for "real" Gradients.
I like your suggestions!

**Comment by pkofod** [comment]
those look much better

**Comment by daschw** [comment]
![theme_default](https://user-images.githubusercontent.com/16589944/34177593-6a39d112-e504-11e7-9cff-5b18c8caf887.png)
![theme_dark](https://user-images.githubusercontent.com/16589944/34177596-6d25b79c-e504-11e7-816f-9a1adbda41c2.png)
![theme_ggplot2](https://user-images.githubusercontent.com/16589944/34177605-7160e6a6-e504-11e7-9c46-8dbc65b7daf3.png)
![theme_juno](https://user-images.githubusercontent.com/16589944/34177629-7d60212e-e504-11e7-832a-abadd22138ce.png)
![theme_lime](https://user-images.githubusercontent.com/16589944/34177613-7586877c-e504-11e7-948a-32f0f96d947e.png)
![theme_orange](https://user-images.githubusercontent.com/16589944/34177643-88c543c8-e504-11e7-8622-abd166f73e68.png)
![theme_sand](https://user-images.githubusercontent.com/16589944/34177640-86233cec-e504-11e7-9046-841a40877d7b.png)
![theme_solarized](https://user-images.githubusercontent.com/16589944/34177636-83a6664c-e504-11e7-89f4-2fb350fdec15.png)
![theme_solarized_light](https://user-images.githubusercontent.com/16589944/34177634-803e867e-e504-11e7-8a09-50ec09b3112d.png)
![theme_wong](https://user-images.githubusercontent.com/16589944/34177654-90f2c4da-e504-11e7-8c4e-1f02b9fa7a21.png)
![theme_wong2](https://user-images.githubusercontent.com/16589944/34177647-8bd7d116-e504-11e7-81a4-6ef7ccb0a7ed.png)

**Comment by pkofod** [comment]
clap clap clap! good job!

**Comment by daschw** [comment]
### `:default`
![theme_default](https://user-images.githubusercontent.com/16589944/70847841-7ca7ea00-1e69-11ea-851e-e99d8559260d.png)

### `:dark`
![theme_dark](https://user-images.githubusercontent.com/16589944/70847843-8d586000-1e69-11ea-9e39-5d4c44865750.png)

### `:ggplot2`
![theme_ggplot2](https://user-images.githubusercontent.com/16589944/70847847-99442200-1e69-11ea-9ae8-ddd10ec4a303.png)

### `:juno`
![theme_juno](https://user-images.githubusercontent.com/16589944/70847860-be389500-1e69-11ea-88b9-2a3bb3bbcf64.png)

### `:lime`
![theme_lime](https://user-images.githubusercontent.com/16589944/70847863-c55fa300-1e69-11ea-8de7-3ef2a3a8ce30.png)

### `:orange`
![theme_orange](https://user-images.githubusercontent.com/16589944/70847866-cf81a180-1e69-11ea-813a-7e4394311ef2.png)

### `:sand`
![theme_sand](https://user-images.githubusercontent.com/16589944/70847868-d4deec00-1e69-11ea-8aab-de94af02bbfe.png)

### `:solarized`
![theme_solarized](https://user-images.githubusercontent.com/16589944/70847869-dad4cd00-1e69-11ea-930e-b145e19bcff5.png)

### `:solarized_light`
![theme_solarized_light](https://user-images.githubusercontent.com/16589944/70847872-df998100-1e69-11ea-955a-7fcc2e7043de.png)

### `:wong`
![theme_wong](https://user-images.githubusercontent.com/16589944/70847875-e58f6200-1e69-11ea-904d-d4f7e27bb181.png)

### `:wong2`
![theme_wong2](https://user-images.githubusercontent.com/16589944/70847880-eaecac80-1e69-11ea-9b59-cdf937427121.png)

### `:gruvbox_dark`
![theme_gruvbox_dark](https://user-images.githubusercontent.com/16589944/70847882-f049f700-1e69-11ea-94f8-255f2cd17288.png)

### `:gruvbox_light`
![theme_gruvbox_light](https://user-images.githubusercontent.com/16589944/70847885-fb048c00-1e69-11ea-9546-4dc0d9e4154c.png)
